# システム全体の設定
system:
  name: "YourselfLM"
  version: "1.0.0"
  environment: "development"  # development, staging, production
  debug: true
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL

# llama.cppの設定
llama:
  runtime_config:
    model_path: "models/gemma-3-1b-it-Q4_K_M.gguf"  # モデルファイルのパス
    # model_path: "C:/Users/omede/.lmstudio/models/lmstudio-community/gemma-3-1b-it-GGUF/gemma-3-1b-it-Q4_K_M.gguf"  # モデルファイルのパス
    n_ctx: 4096              # コンテキストウィンドウサイズ
    n_batch: 200             # バッチサイズ
    n_threads: 4             # CPUスレッド数
    n_gpu_layers: -1         # GPUレイヤー数（GPU使用時）
    temperature: 0.7         # 生成時の温度
    top_p: 0.95              # トップPサンプリング
    top_k: 40                # トップKサンプリング
    repeat_penalty: 1.1      # 繰り返しペナルティ
    stop_sequences:          # 生成停止シーケンス
      - "</s>"
      - "Human:"
      - "Assistant:"

# データベース設定
database:
  type: "sqlite"            # sqlite, postgresql
  path: "data/bot_database.db"  # SQLiteの場合のパス
  # PostgreSQLの場合の設定
  # host: "localhost"
  # port: 5432
  # name: "yourselflm"
  # user: "yourselflm_user"
  # password: "your_password"

# キャッシュ設定
cache:
  person_data:
    max_size: 1000          # キャッシュの最大エントリ数
    ttl: 3600              # キャッシュの有効期間（秒）
  token:
    max_size: 5000         # トークンキャッシュの最大サイズ
    ttl: 7200             # トークンの有効期間（秒）

# Person Data設定
person_data:
  tags:
    - "幼少期に何があったか"
    - "周囲の人の様子"
    - "コンプレックス等の自分のあまり伝えなかった点"
    - "性格の特徴"
    - "信念・価値観"
    - "趣味・興味"
    - "対人関係のスタイル"
    - "感情の反応"
    - "理想・夢"
    - "過去の失敗と学び"
    - "内面の葛藤"
    - "感情のトリガー"
    - "行動のパターン"
    - "思考プロセス"
    - "言動の癖"
    - "価値観の変遷"
    - "自己認識"
    - "対立と解決の方法"
    - "対人関係の歴史"
    - "将来への不安と希望"
  sensitivity_levels:
    - "low"
    - "medium"
    - "high"
    - "very_high"
    - "extremely_high"

# セキュリティ設定
security:
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation_days: 30
  token:
    expiration_hours: 24
    refresh_threshold_hours: 4

# バックアップ設定
backup:
  enabled: true
  schedule: "0 0 * * *"  # 毎日0時にバックアップ
  retention_days: 7
  path: "backups/"
  compression: true

# メトリクス設定
metrics:
  enabled: true
  collection_interval: 60  # 秒
  storage:
    type: "prometheus"    # prometheus, graphite
    # Prometheusの場合の設定
    # host: "localhost"
    # port: 9090

# ログ設定
logging:
  file: "logs/bot.log"
  max_size: 10485760     # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# API設定（必要な場合）
api:
  enabled: true
  host: "localhost"
  port: 8000
  cors:
    allowed_origins:
      - "http://localhost:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"

