# questionData.yaml

presentation_order:
  - hobbies_interests #6
  - personality_traits #4
  - beliefs_values #5
  - influential_people #2
  - significant_childhood_experiences #1
  - past_failures_learnings #10
  - evolution_of_values_turning_points #16
  - self_perception_self_esteem #17
  - emotional_triggers #12
  - emotional_reaction_patterns #8
  - inner_complexes_traumas #3
  - thought_processes_cognitive_biases #14
  - verbal_nonverbal_tics_indicated_thoughts #15
  - interpersonal_style #7
  - relationship_history_adaptation #19
  - conflict_resolution_style #18
  - behavioral_patterns_underlying_needs #13
  - aspirations_dreams #9
  - future_outlook_anxieties_hopes #20
  - internal_conflicts_coping #11

question_themes:
  hobbies_interests: # タグNo.6
    display_name: "趣味・興味関心"
    definition: "個人の余暇時間の過ごし方、純粋に楽しいと感じること、情熱を注げる活動、知的好奇心を刺激される対象。成功体験や他者からの賞賛がきっかけで発展したものも含む。"
    input_examples:
      - "週末は登山に行くのが趣味で、自然の中でリフレッシュしている。"
      - "最近はAIイラストの作成に夢中になっている。"
      - "歴史小説を読むのが好きで、特に古代ローマ史に興味がある。"
    question_prompts_for_ai:
      - "最近、何か夢中になっていることや、楽しいと感じる活動はありますか？"
      - "あなたの知的好奇心をくすぐるものは何ですか？"
      - "どんなことをしている時が、一番リフレッシュできますか？"
      - "あなたの趣味や興味関心について、始めたきっかけや、そこから何を得ているか教えていただけますか？"
    related_person_data_key: "hobbies_interests"
    notes: "「好き」と「得意」は必ずしも一致しない。「成功体験」と結びつけて記述するよう促すと、より自己理解に繋がる情報が得られる可能性。"
    original_tag_id: 6

  personality_traits: # タグNo.4
    display_name: "性格の特徴 (Big Five等)"
    definition: "Big Five（開放性、誠実性、外向性、協調性、神経症的傾向）などの心理学的なフレームワークを用いた自己の性格特性の分析、またはそれに基づいた自己認識。"
    input_examples:
      - "Big Fiveでは外向性が高く、人と接するのは好きだが、誠実性はやや低めで計画性に欠けるところがある。"
      - "MBTIではINTP。論理的思考を好むが、感情表現は苦手。"
      - "自己分析では、好奇心旺盛だが飽きっぽい性格だと思う。"
    question_prompts_for_ai:
      - "ご自身の性格について、どのように捉えていますか？ もしBig FiveやMBTIなどの診断を受けたことがあれば、その結果についても教えていただけますか？"
      - "あなたの性格の長所や、もう少し改善したいと思っている点はありますか？"
      - "周りの人からは、どんな性格だと言われることが多いですか？"
    related_person_data_key: "personality_traits"
    notes: "特定の性格検査フレームワークの知識をユーザーが持っている必要がある。自己評価の客観性には限界がある。「自己認識」タグとの関連性が高い。"
    original_tag_id: 4

  beliefs_values: # タグNo.5
    display_name: "信念・価値観"
    definition: "個人の行動や判断の軸となる、重要だと信じていること、譲れない考え方、人生で何を最も大切にしているかという価値基準。成功体験や失敗体験から形成されたものも含む。"
    input_examples:
      - "常に誠実であることを最も大切にしている。"
      - "挑戦し続けることが成長に繋がると信じている。"
      - "家族との時間を何よりも優先したいという価値観を持っている。"
    question_prompts_for_ai:
      - "あなたが人生で最も大切にしていることは何ですか？"
      - "あなたの行動や判断の軸となるような、譲れない考え方や信念があれば教えてください。"
      - "どのような経験から、現在のあなたの価値観は形作られてきたと思いますか？"
    related_person_data_key: "beliefs_values"
    notes: "抽象的な概念のため、具体的に記述するのが難しい場合がある。「コンプレックス」「過去の失敗と学び」「価値観の変遷」など、他の要素から形成される側面が強い。"
    original_tag_id: 5

  influential_people: # タグNo.2
    display_name: "影響を受けた周囲の人々"
    definition: "自身の成長過程や価値観形成において、特に影響を受けたと感じる人物（親、兄弟姉妹、親戚、友人、教師、上司など）の思想、言動、状態、およびその人物との関係性。"
    input_examples:
      - "母は常に前向きで、その楽観的な性格に救われた。"
      - "中学時代の恩師の一言が、今の職業を選ぶきっかけになった。"
      - "厳格だった父の教育方針には反発も感じたが、社会の厳しさを教えてくれた。"
    question_prompts_for_ai:
      - "あなたの人生で、特に大きな影響を受けたと感じる方はいらっしゃいますか？ どのような影響を受けましたか？"
      - "あなたの価値観や考え方に影響を与えた人物の、印象的な言葉や行動があれば教えてください。"
      - "ロールモデルとしている方や、尊敬する人物はいらっしゃいますか？その方のどのような点に惹かれますか？"
    related_person_data_key: "influential_people"
    notes: "記述が主観的になりがち。複数の人物について記述する場合、情報が散漫になる可能性。「対人関係のスタイル」「対人関係の歴史」との境界を意識する必要。"
    original_tag_id: 2

  significant_childhood_experiences: # タグNo.1
    display_name: "幼少期の重要体験"
    definition: "幼少期（おおむね小学生くらいまで）に経験し、現在も記憶に残っている、人格形成や価値観に大きな影響を与えたと考えられる出来事や経験。"
    input_examples:
      - "両親が共働きで寂しい思いをしたが、その分自立心が育まれたと思う。"
      - "初めての海外旅行で異文化に触れ、世界への興味が大きく広がった。"
      - "いじめられた経験から、人の痛みに敏感になった。"
    question_prompts_for_ai:
      - "子供の頃のことで、今のあなたの人格や価値観に影響を与えたと思うような、特に記憶に残っている出来事はありますか？"
      - "幼少期に経験したことで、今のあなたを作っていると感じる体験があれば教えてください。それはポジティブなものでも、困難だったものでも構いません。"
    related_person_data_key: "significant_childhood_experiences"
    notes: "記憶の曖昧さ、美化、歪曲の可能性。非常にセンシティブな内容を含む可能性。他のタグ（例：コンプレックス、失敗と学び、価値観の変遷）と内容が重複しやすい。"
    original_tag_id: 1

  past_failures_learnings: # タグNo.10
    display_name: "過去の失敗と学び"
    definition: "これまでに経験した重要な失敗と、その原因分析、失敗から得た教訓や気づき。課題への向き合い方、自己成長にどう繋げた（または繋げられなかった）かのプロセス。"
    input_examples:
      - "大学受験で第一志望に不合格だったが、計画性の重要さを学んだ。"
      - "プロジェクトで大きなミスをしたが、チームワークと報告の必要性を痛感した。"
      - "友人を傷つけてしまい、言葉の重みを学んだ。"
    question_prompts_for_ai:
      - "これまでの人生で、何か大きな失敗だと感じた経験はありますか？ その経験から何を学びましたか？"
      - "困難な状況や失敗に直面した時、あなたはどのように向き合い、乗り越えようとしますか？"
      - "過去の失敗が、今のあなたの考え方や行動にどのように活かされていると感じますか？"
    related_person_data_key: "past_failures_learnings"
    notes: "失敗経験の開示には抵抗がある場合も。「幼少期の重要体験」「コンプレックス」と関連しやすい。学びの深さや客観性には個人差がある。"
    original_tag_id: 10

  evolution_of_values_turning_points: # タグNo.16
    display_name: "価値観の変遷と契機"
    definition: "人生を通じて、個人の価値観がどのように変化してきたか、そのターニングポイントとなった出来事や経験。特に大きな影響を与えた「衝撃的な記憶」やエピソード。"
    input_examples:
      - "若い頃はキャリアが全てだったが、出産を機に家族との時間を最優先するようになった。"
      - "大きな挫折を経験し、結果よりも過程を大切にする価値観に変わった。"
    question_prompts_for_ai:
      - "あなたの価値観は、人生のステージや経験によってどのように変化してきたと感じますか？"
      - "特にご自身の価値観が大きく変わるきっかけとなった、ターニングポイントのような出来事があれば教えてください。"
      - "昔は大切にしていたけれど今はそうでもない価値観や、逆に昔は重視していなかったけれど今は大切にしている価値観はありますか？"
    related_person_data_key: "evolution_of_values_turning_points"
    notes: "「信念・価値観」のダイナミクス版。「幼少期の重要体験」「過去の失敗と学び」などと深く関連。「衝撃の記憶」に焦点があり、トラウマティックな内容が含まれる可能性。"
    original_tag_id: 16

  self_perception_self_esteem: # タグNo.17
    display_name: "自己認識と自己肯定感"
    definition: "自分自身をどのような存在だと捉えているか、自分の長所・短所、能力、役割、価値についての総合的な自己評価。自分自身をどれくらい肯定的に受け入れているか（自己肯定感）。"
    input_examples:
      - "自分は計画性があり目標達成力は高いが、共感力は低いと認識している。"
      - "周りからは明るいと言われるが、内心では自信がなく、自己肯定感は低い方だ。"
    question_prompts_for_ai:
      - "あなたは自分自身のことを、どのような人間だと認識していますか？ 長所や短所も含めて教えていただけますか？"
      - "自分の能力や役割について、どのように評価していますか？"
      - "自分自身をどれくらい受け入れていると感じますか？ 自己肯定感について、どのように感じていますか？"
    related_person_data_key: "self_perception_self_esteem"
    notes: "「性格の特徴 (Big Five等)」と重複する部分が多いが、こちらはより主観的・総合的な自己イメージ。「コンプレックス」とも関連。自己評価の客観性には限界がある。"
    original_tag_id: 17

  emotional_triggers: # タグNo.12
    display_name: "感情のトリガー"
    definition: "喜怒哀楽といった特定の感情を強く引き起こす、具体的な出来事、言葉、状況、記憶、または身体的・精神的な内的要因と、誰かが賞に受かった、親密な人が交通事故にあったなどの外的な要因。"
    input_examples:
      - "人から認められると強い喜びを感じる。"
      - "不公平な扱いを受けると激しい怒りを覚える。"
      - "大切な人との別れを思い出すと深い悲しみに襲われる。"
      - "締め切りが迫ると強い不安を感じる。"
      - "小学生からの付き合いの友達が暴走したトラックに轢かれて脳や内臓が見えてぐちゃぐちゃな状態で自分はそのそばにいて強いフラッシュバックと守れなかった悔しさだけが募った"
    question_prompts_for_ai:
      - "どのような時に、特に強い喜びや楽しさを感じますか？"
      - "逆に、どんな状況や言葉、出来事が、あなたを怒らせたり、悲しませたり、不安にさせたりしやすいですか？"
      - "特定の記憶や過去の経験が、ふとした瞬間に強い感情を呼び起こすことはありますか？"
    related_person_data_key: "emotional_triggers"
    notes: "「感情の反応パターン」と非常に似ているが、こちらは「何が原因で」というトリガーそのものに焦点。多岐にわたるため、網羅的に記述するのは難しい。"
    original_tag_id: 12

  emotional_reaction_patterns: # タグNo.8
    display_name: "感情の反応パターン"
    definition: "特定の状況や出来事に対し、どのような感情が強く喚起され、その結果どのような行動を取りやすいかという、記憶に残っている顕著な感情と行動の結びつきのパターン。"
    input_examples:
      - "批判されると強い怒りを感じ、反論せずにいられなくなる。"
      - "目標を達成した時は大きな喜びを感じ、さらに高い目標に挑戦したくなる。"
      - "予期せぬトラブルが起きるとパニックになり、思考が停止してしまう。"
    question_prompts_for_ai:
      - "あなたが特定の感情（例：怒り、喜び、不安）を強く感じた時、典型的にはどのような行動をとりやすいですか？"
      - "何か嬉しいことがあった時、それをどのように表現したり、次につなげたりしますか？"
      - "ストレスを感じたり、困難な状況に陥ったりした時、あなたの感情と行動はどのように連動する傾向がありますか？"
    related_person_data_key: "emotional_reaction_patterns"
    notes: "「感情のトリガー」と非常に近いが、こちらは「反応と行動のセット」に焦点。記憶に依存するため、バイアスがかかる可能性。"
    original_tag_id: 8

  inner_complexes_traumas: # タグNo.3
    display_name: "内面のコンプレックス・トラウマ"
    definition: "自身が劣等感、弱み、トラウマと感じていること。過去の大きな失敗、ショックな出来事、他者に開示しにくい内面的な苦痛や葛藤。無意識的な回避行動や意識的な恐怖の原因。"
    input_examples:
      - "人前で話すことに強い苦手意識があり、重要な場面では声が震えてしまう。"
      - "過去の大きな失恋がトラウマで、新しい恋愛に踏み出せない。"
      - "自分の学歴にコンプレックスがあり、無意識に他人と比較してしまう。"
    question_prompts_for_ai:
      - "もしお話しいただける範囲で構いませんが、ご自身が弱みだと感じていることや、劣等感を抱いている部分はありますか？"
      - "過去の経験で、今でも思い出すと辛い気持ちになったり、ご自身の行動に影響を与えたりしていると感じることはありますか？"
      - "意識的に避けようとしていることや、特定の状況で強い恐怖を感じるようなことはありますか？"
    related_person_data_key: "inner_complexes_traumas"
    notes: "非常にデリケートな情報であり、記述への心理的ハードルが高い。自己開示の度合いに個人差が大きい。「幼少期の重要体験」「過去の失敗と学び」と内容が重複しやすい。"
    original_tag_id: 3

  thought_processes_cognitive_biases: # タグNo.14
    display_name: "思考プロセス・思考の癖"
    definition: "情報を受け取ったり問題に直面したりした際に、どのように考えを進めるか、連想の仕方、思考の道筋や特徴的なパターン（思考の癖）。"
    input_examples:
      - "問題解決の際は、まず全体像を把握し、細部に分解して考える。"
      - "新しいアイデアは、既存の知識を意外な形で組み合わせることで生まれることが多い。"
      - "人の話を深読みしすぎる傾向がある。"
    question_prompts_for_ai:
      - "何か問題に直面した時、あなたはどのように考えを進めて解決しようとしますか？"
      - "情報を得たときや、何かを判断するときに、あなた特有の考え方のパターンや癖のようなものはありますか？"
      - "例えば、物事を楽観的に捉えやすいですか、それとも悲観的に捉えやすいですか？ 直感と論理、どちらを重視する傾向がありますか？"
    related_person_data_key: "thought_processes_cognitive_biases"
    notes: "自身の思考プロセスを客観的に記述するのは非常に高度なメタ認知能力を要する。具体的な例を挙げてもらうことが重要。"
    original_tag_id: 14

  verbal_nonverbal_tics_indicated_thoughts: # タグNo.15
    display_name: "言動の癖と現れる思考"
    definition: "会話や行動において無意識的に繰り返される特徴的な言葉遣い、ジェスチャー、態度など。それらが示唆する可能性のある思考傾向、性格特性、他者へのスタンス、好む役割。"
    input_examples:
      - "話の途中で『要するに』とまとめがち。相手に分かりやすく伝えたい思考の表れかも。"
      - "緊張すると早口になる。自信のなさを隠そうとしているのかもしれない。"
    question_prompts_for_ai:
      - "ご自身の話し方や行動で、何か特徴的な癖（口癖、ジェスチャー、態度など）はありますか？"
      - "そういった癖は、あなたのどのような考えや感情から来ていると思いますか？"
      - "周りの人から、あなたの言動の癖について何か言われたことはありますか？"
    related_person_data_key: "verbal_nonverbal_tics_indicated_thoughts"
    notes: "自己申告だけでなく、他者からのフィードバックも参考にできるとより客観的。「思考プロセス」や「対人関係のスタイル」と関連性が高い。"
    original_tag_id: 15

  interpersonal_style: # タグNo.7
    display_name: "対人関係のスタイル"
    definition: "他者とどのように関わるか、関係性を築く上での基本的な態度や行動傾向。他者をどう認識し、他者から自分がどう見られていると考えているか。SNSなどオンラインでの関わり方も含む。"
    input_examples:
      - "初対面の人とも物怖じせず話せるが、深い関係になるには慎重なタイプ。"
      - "信頼できる人には心を開くが、そうでない人には警戒心が強い。"
      - "SNSでは共感を求める投稿をしがちだ。"
    question_prompts_for_ai:
      - "あなたは普段、他の人とどのように関わることが多いですか？ 例えば、初対面の人との接し方や、親しい友人との関係の築き方など。"
      - "オンライン（SNSなど）とオフラインでの人との関わり方に違いはありますか？"
      - "人付き合いにおいて、あなたが心地よいと感じる距離感や関係性はどのようなものですか？"
    related_person_data_key: "interpersonal_style"
    notes: "「周囲の人の様子」「対人関係の歴史」との違いを明確にする必要。自己認識と実際の他者からの評価が乖離している可能性。"
    original_tag_id: 7

  relationship_history_adaptation: # タグNo.19
    display_name: "対人関係の歴史と変化への対応"
    definition: "これまでの人生における重要な他者（信頼できる人、影響を受けた人、苦手だった人など）との関係性がどのように変化し、それに対して自身がどう感じ、どのように対応・適応してきたかの記録。"
    input_examples:
      - "学生時代の親友とは価値観が変わり疎遠になったが、その経験から人間関係は変化するものだと学んだ。"
      - "裏切られた経験から、人を信じるのに時間がかかるようになった。"
    question_prompts_for_ai:
      - "これまでの人間関係で、特に印象に残っている変化（始まった関係、終わった関係、関係性が変わったなど）はありますか？"
      - "そういった関係性の変化に対して、あなたはどのように感じ、どのように対応してきましたか？"
      - "過去の人間関係の経験は、現在のあなたの対人関係の築き方にどのような影響を与えていると思いますか？"
    related_person_data_key: "relationship_history_adaptation"
    notes: "「周囲の人の様子」「対人関係のスタイル」と重複する部分が多いが、こちらは関係性の「変化」と「それへの対応・学習」に焦点。記述が広範囲に及び、整理が難しい場合がある。"
    original_tag_id: 19

  conflict_resolution_style: # タグNo.18
    display_name: "対立時の対応スタイル"
    definition: "他者と意見が衝突したり利害が対立したりした際に、どのような対応を取りやすいか。和解を試みるか、自己主張を貫くか、妥協点を探るかなど、対立解消における特徴的なスタイルや判断基準。"
    input_examples:
      - "対立時はまず相手の意見を最後まで聞き、共通点を探ろうとする。"
      - "自分の正当性が明らかだと思う場合は、相手が納得するまで徹底的に議論する。"
      - "無用な争いは避け、早期解決のために譲歩することも多い。"
    question_prompts_for_ai:
      - "他の人と意見が合わなかったり、対立したりした時、あなたはどのような対応を取りやすいですか？"
      - "対立状況において、自分の意見を主張することと、相手との関係性を保つこと、どちらをより重視する傾向がありますか？"
      - "これまでに経験した対立状況で、うまく解決できたケースや、逆にうまくいかなかったケースがあれば、その時の対応について教えていただけますか？"
    related_person_data_key: "conflict_resolution_style"
    notes: "「対人関係のスタイル」の一部とも言えるが、より「対立時」に特化。「信念・価値観」が解決方法に影響する。自己申告と実際の行動が異なる可能性。"
    original_tag_id: 18

  behavioral_patterns_underlying_needs: # タグNo.13
    display_name: "行動パターンと根底欲求"
    definition: "日常生活における習慣的な行動、生活リズム、健康関連行動（食事、睡眠、運動等）。それらが精神状態や思考に与える影響、およびそれらの行動の根底にあると考えられる欲求。"
    input_examples:
      - "毎朝ジョギングを欠かさない。体調管理と達成感を求めているのだと思う。"
      - "ストレスが溜まると甘いものを過食してしまう。一時的な安心感を求めているのかもしれない。"
    question_prompts_for_ai:
      - "何か毎日続けている習慣や、決まった生活リズムはありますか？ それはあなたの心や体にどんな影響を与えていますか？"
      - "ストレスを感じた時や、気分が落ち込んだ時に、ついやってしまう行動はありますか？ その行動の背景にはどんな気持ちや欲求があると思いますか？"
      - "あなたの日常的な行動（食事、睡眠、運動など）は、あなたの精神状態や思考にどのように関連していると感じますか？"
    related_person_data_key: "behavioral_patterns_underlying_needs"
    notes: "「根底にある欲求」の自己分析は難しい場合がある。「趣味・興味」とも関連するが、こちらはより日常的・習慣的な行動と、その動機に焦点。"
    original_tag_id: 13

  aspirations_dreams: # タグNo.9
    display_name: "理想・夢・自己実現欲求"
    definition: "将来達成したい目標、なりたい自分像、実現したい状態。個人的な願望や社会的な目標など、強い動機付けとなるもの。過去に否定された経験からくる憧れや探求欲も含む。"
    input_examples:
      - "自分の経験を活かして、社会貢献できる事業を立ち上げたい。"
      - "世界中の絶景を巡り、写真集を出版するのが夢だ。"
      - "家族と穏やかで充実した日々を送ることが理想の人生だ。"
    question_prompts_for_ai:
      - "将来、達成したい目標や、なりたい自分像はありますか？"
      - "あなたの夢や、実現したいと強く願っていることは何ですか？ それはいつ頃から持ち始めましたか？"
      - "どのような状態になれば、あなたは「自己実現できた」と感じられると思いますか？"
    related_person_data_key: "aspirations_dreams"
    notes: "現実的な目標から壮大な夢まで幅が広い。時間経過で変化しやすい。「何を否定されたものにもよる」という点は、コンプレックスの裏返しとしての夢を示唆し、デリケートな場合がある。"
    original_tag_id: 9

  future_outlook_anxieties_hopes: # タグNo.20
    display_name: "将来への不安と希望"
    definition: "将来に対して抱いている期待、楽観的な見通し（希望）と、懸念、悲観的な見通し（不安）。具体的にどのような事柄（キャリア、健康、人間関係、社会情勢など）についてそう感じているか。"
    input_examples:
      - "AI技術の発展には大きな希望を感じるが、自分の仕事がなくなるのではないかという不安もある。"
      - "子供たちの成長には希望を感じるが、自身の老後には漠然とした不安がある。"
    question_prompts_for_ai:
      - "ご自身の将来について、どのような希望や期待を持っていますか？"
      - "逆に、将来のことで何か心配なことや、不安に感じていることはありますか？"
      - "キャリア、健康、人間関係、社会の変化など、特定の分野で特に将来への希望や不安を感じることはありますか？"
    related_person_data_key: "future_outlook_anxieties_hopes"
    notes: "「理想・夢」と希望の部分は関連性が高い。「コンプレックス」や「過去の失敗」が不安に繋がる可能性。漠然とした記述になりやすく、具体的な要因まで掘り下げることが重要。"
    original_tag_id: 20

  internal_conflicts_coping: # タグNo.11
    display_name: "内面の葛藤と対処"
    definition: "複数の選択肢、価値観、他者からの期待などの間で揺れ動く内面的な対立やジレンマ。困難な決断を迫られた際の悩み方、対処プロセス、そして最終的な解釈や結論。"
    input_examples:
      - "キャリアと家庭の両立で悩んだ末、時短勤務を選択し、自分なりのバランスを見つけた。"
      - "親友の不正を知り、告発すべきか悩んだが、最終的には正直に話し合うことを選んだ。"
    question_prompts_for_ai:
      - "これまでの人生で、何か大きな決断を迫られたり、複数の選択肢や価値観の間で悩んだりした経験はありますか？"
      - "そういった内面的な葛藤に直面した時、あなたはどのように考え、対処し、結論を出してきましたか？"
      - "現在、何か抱えている悩みや葛藤があれば、お話しいただける範囲で教えていただけますか？"
    related_person_data_key: "internal_conflicts_coping"
    notes: "葛藤の解決プロセスまで詳細に記述してもらうのは難しい場合がある。「信念・価値観」と密接に関連。非常にプライベートな内容を含む可能性がある。"
    original_tag_id: 11